PROMPT_ASKLLM_EN = """Does the following paragraph demarcated within ### and ### contain informative signal for pre-training a large-language model in {language}?
An informative datapoint should be well-formatted, contain some usable knowledge of the world, and not have any autogenerated or autotranslated marketing, etc. content.

OPTIONS:

- yes
- no

###
{extract}
###
"""

PROMPT_ASKLLM_SV = """Innehåller följande stycke avgränsat inom ### och ### informativ signal för pre-träning av en stor språkmodell på svenska?
En informativ datapunkt bör vara välformaterad, innehålla användbar kunskap om världen och inte ha något automatiskt genererat eller automatiskt översatt innehåll som marknadsföring, etc.

ALTERNATIV:

- ja
- nej

###
{extract}
###
"""

PROMPT_ASKLLM_NO = """Inneholder følgende avsnitt avgrenset innen ### og ### informativt signal for pre-trening av en stor språkmodell på norsk?
Et informativt datapunkt bør være godt formatert, inneholde brukbar kunnskap om verden og ikke ha noe automatisk generert eller automatisk oversatt innhold som markedsføring, etc.

ALTERNATIVER:

- ja
- nei

###
{extract}
###
"""

PROMPT_ASKLLM_DA = """Indeholder følgende afsnit afgrænset inden for ### og ### informativt signal til prætræning af en stor sprogmodel på dansk?
Et informativt datapunkt bør være velstruktureret, indeholde brugbar viden om verden og ikke indeholde noget automatisk genereret eller automatisk oversat indhold som markedsføring osv.

MULIGHEDER:

- ja
- nej

###
{extract}
###
"""
